### PR TITLE
Enforce Zig version for `build.zig`

### PR DESCRIPTION
**Pull request by Rexicon226**
this is how you do it :)

I'm very happy to see you guys using zig 👍 

We had a massive build system overhaul a couple of days ago (ziglang/zig#18160) and if you'd like, I could port you guys over. You'll need to do it at some point if you wish to complete the todo: 
> update to zig v0.12 final (when released)

### CODE REVIEW

**Comment by ivmai** [comment]
Thank you!
I think we need to replace == with >= for the required version comparison.

**Comment by ivmai** [comment]
> We had a massive build system overhaul a couple of days ago (https://github.com/ziglang/zig/pull/18160) and if you'd like, I could port you guys over.

Sure!

**Comment by Rexicon226** [comment]
> Thank you! I think we need to replace == with >= for the required version comparison.

Sure. I just read the comment as "assuming" a specific version, and made it `eq`. Most people now do use `gt` 👍

**Comment by ivmai** [comment]
if (builtin.zig_version.order(required_zig) != .eq)
->
if (builtin.zig_version.order(required_zig) == .lt)

Right? I'll fix it

**Comment by Rexicon226** [comment]
> if (builtin.zig_version.order(required_zig) != .eq) -> if (builtin.zig_version.order(required_zig) == .lt)
> 
> Right? I'll fix it

Yep, but don't worry. I included it in the update to zig master 👍

**Comment by ivmai** [comment]
Merged all commits with some modifications - c535d0f, 9566d70, 98e4d0a

**Pull request closed without merging**
