### PR TITLE
Fix undefined reference to "__data_start" on AArch64

### PR DESCRIPTION
**Pull request by davidebeatrici**
Related: #294

### CODE REVIEW

**Comment by ivmai** [comment]
Thank you. Committed as e08f63c1c.

**Comment by davidebeatrici** [comment]
Thank you for merging!

**Comment by ivmai** [comment]
Could you please explain where have you met the issue? Which distro?
I'm asking because Linux/aarch64 was added long time ago (commit 7b5acfba9, Jan 2013).

**Comment by davidebeatrici** [comment]
OpenMandriva: https://abf.openmandriva.org/build_lists/223411

```c
ld.lld: error: undefined symbol: __data_start
>>> referenced by dyn_load.c:629 (/builddir/build/BUILD/gc-8.2.0/extra/../dyn_load.c:629)
>>>               lto.tmp:(GC_stopped_mark)
>>> referenced by dyn_load.c:629 (/builddir/build/BUILD/gc-8.2.0/extra/../dyn_load.c:629)
>>>               lto.tmp:(GC_stopped_mark)
>>> referenced by os_dep.c:2103 (/builddir/build/BUILD/gc-8.2.0/extra/../os_dep.c:2103)
>>>               lto.tmp:(GC_register_data_segments)
>>> referenced 5 more times
```

It's the same error @tpgxyz encountered (https://github.com/ivmai/bdwgc/issues/294#issuecomment-671335477).

**Comment by ivmai** [comment]
Got it, thank you

**Comment by davidebeatrici** [comment]
You're welcome.

**Pull request closed without merging**
