### PR TITLE
Remove GC_OPENBSD_UTHREADS support

### PR DESCRIPTION
**Pull request by blackgnezdo**
This will never be relevant now that 2012 is well behind the 1 year support horizon for OpenBSD.

### CODE REVIEW

**Comment by blackgnezdo** [comment]
I tested this on OpenBSD-7.2-current on amd64 by running these commands:
```
AUTOMAKE_VERSION=1.16 AUTOCONF_VERSION=2.71 ./autogen.sh && \
./configure --with-libatomic-ops=no  --enable-cplusplus \
  --enable-threads=pthreads  --enable-mmap  --enable-static=yes && \
gmake
gmake check
```

**Comment by ivmai** [comment]
Thank you for the PR.
Is there any chance OpenBSD to return support of  that ancient functionality? Removing of this code should not be difficult. But signal-based approach of stopping threads is bad one compared to that one in ancient OpenBSD.

**Comment by ivmai** [comment]
Similar PR to remove the support of ancient OpenBSD - https://github.com/ivmai/bdwgc/pull/347/commits/a4bcba149199ab03feed6f84ecc25b2a7f94f88b

**Comment by ivmai** [comment]
I'd prefer to keep this code (under ifdef) for now just in case it would be needed in the future for some other OS.

**Comment by blackgnezdo** [comment]
No, I can't see how uthreads could return in the future. And even if that happens, the extra work of reverting this commit will be lower than the drag in the meantime.

**Comment by blackgnezdo** [comment]
> I'd prefer to keep this code (under ifdef) for now just in case it would be needed in the future for some other OS.

This code is never compiled, so the difference is it rots while confusing people. I started on this patch because I was confused by the usage of `__syscall`.

**Comment by ivmai** [comment]
Okay, I got your point. Let me think more about.

**Comment by ivmai** [comment]
Is my understanding correct that stopping threads with pthread_suspend_np is no longer supported by OpenBSD (i.e. passing -DGC_OPENBSD_THREADS to CFLAGS results in a compilation or runtime failure?

**Comment by blackgnezdo** [comment]
`pthread_suspend_np` is [nowhere in the OpenBSD source tree](https://github.com/openbsd/src/search?q=pthread_suspend_np&type=code). Though I was unable to cause any failures by plugging  -DGC_OPENBSD_THREADS into CFLAGS.

**Comment by ivmai** [comment]
> `pthread_suspend_np` is [nowhere in the OpenBSD source tree](https://github.com/openbsd/src/search?q=pthread_suspend_np&type=code). 

Got it.

**Comment by ivmai** [comment]
I've merged your patch after some reformatting.

**Comment by blackgnezdo** [comment]
Great, thanks. Appreciate the shout-out among authors.

**Pull request closed without merging**
