### PR TITLE
Make compile on ARM macs with tinyc

### PR DESCRIPTION
**Pull request by medvednikov**
As discussed in https://github.com/ivmai/bdwgc/issues/646

### CODE REVIEW

**Comment by ivmai** [comment]
Sorry for a delay.
Which tcc version do you use?

**Comment by ivmai** [comment]
Also, I think it would be better to make a workaround to GC_reachable_here() definition, not REACHABLE_AFTER_DIRTY(). (I can change it myself.)

**Comment by medvednikov** [comment]
We use the latest build from their `mob` branch. The don't do versioned releases often.

> Also, I think it would be better to make a workaround to GC_reachable_here() definition, not REACHABLE_AFTER_DIRTY()
Yes, that's a better place. Thanks.

**Comment by ivmai** [comment]
> Which tcc version do you use?

I mean I'd like to put tcc version in the comment near the workaround.
I guess you use tcc-0.9.27, right? (https://download.savannah.nongnu.org/releases/tinycc/)

**Comment by medvednikov** [comment]
```
tcc -v
tcc version 0.9.28rc
```

**Comment by ivmai** [comment]
OK (https://github.com/TinyCC/tinycc/blob/mob/VERSION)

**Comment by ivmai** [comment]
Merged with some modifications. Please test.

**Pull request closed without merging**
