### PR TITLE
Receiving void* instead of char* is easier to use, as it requires no casting.

### PR DESCRIPTION
**Pull request by jaykrell**
Small downside is anyone using decltype(GC_push) in C++ function signatures
will get different name mangling.

### CODE REVIEW

**Comment by ivmai** [comment]
Please fix build failures, and also revise all GC_push_all/all_eager/conditional calls to remove unneeded casts.

**Comment by jaykrell** [comment]
The casts are ok, but now optional, esp. in clients. But ok, and definitely failures.

**Comment by jaykrell** [comment]
Hm, so volatile x* doesn't go silently to void*, either a) cast sometimes, when there is volatile, which will be rare, or b) change the parameters to volatile void*, which is my very slight preference.

**Comment by ivmai** [comment]
> Hm, so volatile x* doesn't go silently to void*, either a) cast sometimes, ...

Yes, like done in GC_clear_stack_inner() (in misc.c) for a BZERO/memset call:
      BZERO((/* no volatile */ void *)dummy, sizeof(dummy));

**Comment by ivmai** [comment]
Merged (with some changes) as b2b0d27

**Pull request closed without merging**
