### PR TITLE
Implementation of heap walking code where the caller passes a callback

### PR DESCRIPTION
**Pull request by drmeister**
I've set up the heap walking code to accept a callback provided by the caller.

### CODE REVIEW

**Comment by drmeister** [comment]
Hi Ivan - another friendly ping regarding adding this to the boehm repository

**Comment by ivmai** [comment]
Hi Christian,
I will definitely look at it

**Comment by drmeister** [comment]
Ivan - excellent - thank you very much.

**Comment by drmeister** [comment]
Ivan, another friendly ping about whether this could be pulled into the Boehm repository

**Comment by ivmai** [comment]
I have merged 1st commit to master (with almost none modifications). The 2nd commit has been completely rewritten (and a test has been added). See a20fa51 and 84fcf4c

**Pull request closed without merging**
