### PR TITLE
Minor build.zig improvements

### PR DESCRIPTION
**Pull request by linusg**

### CODE REVIEW

**Comment by ivmai** [comment]
Okay, thank you, I will review and test it in several days.

**Comment by ivmai** [comment]
Is this working with zig v0.12.0? If not (but working with 0.13.0) then we need to update zig_min_required_version.

**Comment by linusg** [comment]
This uses no recent features and will work with Zig 0.12, yes.

**Comment by ivmai** [comment]
Merged.

**Pull request closed without merging**
