### PR TITLE
Add ARC support

### PR DESCRIPTION
**Pull request by vineetgarc**
Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

### CODE REVIEW

**Comment by vineetgarc** [comment]
@linux-snps-arc@lists.infradead.org

**Comment by vineetgarc** [comment]
ping !

**Comment by ivmai** [comment]
Hi. The patch seems to be good. I'm sorry for a big delay, I will process all pending PRs in June.

**Comment by vineetgarc** [comment]
OK thx. FWIW this patch is part of effort to bootstrap Debian on ARC.

**Comment by ivmai** [comment]
Thank you. I merged it with some modification (COUNT_UNMAPPED_REGIONS is defined).

**Pull request closed without merging**
