### PR TITLE
Update README.cmake

### PR DESCRIPTION
**Pull request by rdp**
Add description of how to install via cmake.

### CODE REVIEW

**Comment by ivmai** [comment]
Thank you. Committed with come changes as a6b6720

**Comment by ivmai** [comment]
BTW. Just if you have time and will, it would be better to convert this readme (as well as other non-platform readme files) to .md

**Comment by rdp** [comment]
Thanks.  I'm not exactly sure how to convert them, or are you thinking just the filenames?

**Comment by ivmai** [comment]
Yes, the minimum is to rename (remove "README.", add .md) and update links. The rest is a creative work to make it better readable if viewed on github - to insert formatting symbols where appropriate (like `code`) and convert to links if other doc files are mentioned in these files

**Pull request closed without merging**
