### PR TITLE
Update README.emscripten

### LINKED ISSUE #650: Emscripten support fundamentally broken?
### Summary

I recently encountered an issue with bdwgc in emscripten where pointers "on the stack" (reason for quotation marks is explained below) are not found during the marking phase and thus memory is released too early. I believe that this is a not a simple bug but rather a fundamental issue that cannot be resolved without cooperation from the emscripten C compiler.

### A test case

A simple test program which shows the issue is as follows:

```C
#include <stdio.h>
#include "gc/gc.h"

struct list {
   int value;
   struct list *rest;
};

void print_list(struct list *p) {
   while (p->rest != NULL) {
      printf("%d ", p->value);
      p = p->rest;
   }
   printf("\n");
}

int main() {
   printf("Starting to allocate\n");
   struct list *head = GC_MALLOC(sizeof(struct list));
   struct list *p = head;
   head->value = 0;
   for (int i = 1; i < 10000; i++) {
      struct list *q = GC_MALLOC(sizeof(struct list));
      q->value = i;
      p->rest = q;
      p = q;
   }
   p->rest = NULL;
   print_list(head);
   return 0;
}
```

If everything works correctly, this should just print the numbers from 0 to 9999. But when compiled with `emcc -O2 test.c libgc.a -o test.html -sASYNCIFY` and run in node or in a web browser, it only prints numbers from 8192 upwards. The reason for the failure is that bdwgc does not find the `head` pointer during the marking phase and thus frees the entire list too early, reusing the  memory for later allocations.

### Why I think this issue is unsolvable without changes in the emscripten C compiler

Unlike ordinary assembly languages, webassembly does not have a fixed register file. Instead, there is the concept of a "local". These locals effectively behave as an unlimited number of registers which are automatically saved and restored before/after function calls by the wasm virtual machine. The `head` pointer in the test case is stored in such a local variable. These are not scanned by bdwgc and thus memory is reclaimed too early. However, to the best of my knowledge, there is no way to access the value of locals for functions further up the call stack. They are not saved on the same stack that emscripten uses and which bdwgc does scan for pointers, but rather in a memory space that is internal to the wasm VM.

Therefore, the issue does not seem to be solvable without instructing the C compiler to always keep pointers on a stack which is accessible to bdwgc. This usually happens when compiling with `-O0` (the above test case works correctly in this case), but I have also encountered examples where even with `-O0` pointers are not kept on the emscripten stack.

Unless there is some way around the problem that I did not think of, in my opinion it would be useful to warn about this issue in the documentation, if not remove the broken emscripten support altogether.

### PR DESCRIPTION
**Pull request by spaghettisalat**
Closes #650

### CODE REVIEW

**Comment by ivmai** [comment]
@jul Do you agree with the readme change?

**Comment by jul** [comment]
wrong @jul « same player shoot again »©

**Comment by juj** [comment]
I would recommend expanding on the comment a little bit.. right now it might give a misimpression that adding the spill-pointers pass or scanning the stack would be unconditionally required - which it isn't, if user only triggers a GC at points when it is known there are no managed objects on the stack.

So I would recommend stating the readme in a way that would illustrate that there are these two strategies that one can use, and also illustrate about the drawbacks of each. The challenge with using --spill-pointers is that it greatly increases generated code size on disk, and there may also be a small % performance penalty to doing so.

**Comment by spaghettisalat** [comment]
Do you have some example code for the strategy where one triggers the GC only at specific points which we can link to in the README? I guess this requires some modifications of the bdwgc source code to avoid the automatic GC runs, right?

At the moment, your description of how this strategy works is somewhat cryptic to me and therefore it is hard for me to write a good summary for the README.

**Comment by ivmai** [comment]
GC_disable() might be useful to avoid automatic GC

**Comment by juj** [comment]
Yeah, `GC_disable()`, and then one can trigger an asynchronous GC e.g. by using [emscripten_set_timeout()](https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/eventloop.h#L18) function that calls to a callback that manually runs `GC_collect();` (I forget if bdwgc requires one to call GC_enable() before calling GC_collect() manually?)

**Comment by ivmai** [comment]
> I forget if bdwgc requires one to call GC_enable() before calling GC_collect() manually?

Yes, GC_enable() is needed otherwise GC_collect() is no-op.

**Comment by spaghettisalat** [comment]
Alright, I have extended the description in the README file a bit. I hope that should do it.

**Comment by juj** [comment]
Looks really good!

**Comment by ivmai** [comment]
Merged.

**Pull request closed without merging**
